### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by claire-kz** [aharrisonwatt/Session_Finder#2]
- Create events needs to be MVP
- Having a map needs to be MVP
- Auth needs to be frontend
- Phase 2: notes model?  Do you have notes or is this from demo docs?
- Phase 2: should only take 1 day 
- Implementation timeline needs to be reworked.  Priorities should not be tagging and seeding.  Let's make event CRUD the a top priority - that should be done by end of week one, if not sooner.  I think next should be map integration (showing where an event is planned), then search, users homepage, and landing page.  Seed a little as you go, adding more information as needed to test functionality.

**Comment by aharrisonwatt** [comment]
What does 'Auth needs to be frontend' mean?
What is a users homepage? like a profile?

**Comment by aharrisonwatt** [comment]
for MVP I have this written on line 14.  Would you like me to break it out into separate lines?

- [ ] The minimally necessary features for an AirBnB-inspired site: Event Creation, Map integration showing location of events, filtering events based on a number of factors
